version: "2"
services:
  nginx:
    image: nginx:1.15.2
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./mateovergara_app:/app

  postgres:
    image: postgres:12
    env_file: .env

  app:
    image: mateovergara_web
    build: ./mateovergara_app
    volumes:
      - ./mateovergara_app:/app
    env_file: .env
    restart: on-failure
    command: sh ./scripts/dev.sh
