version: "2"
services:
  nginx:
    image: nginx:1.15.2
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./mateovergara_app:/app

  db:
    image: postgres:12

    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'mateovergara_sql'
      POSTGRES_USER: 'mavergarah'
      POSTGRES_PASSWORD: 'S4F3RL1N1B4'
    ports:
      - "5432:5432"

  app:
    image: mateovergara_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file: .env
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
