# Generated by Django 4.1.1 on 2024-10-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Title')),
                ('photo', models.ImageField(max_length=256, upload_to='uploads', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'MV_Photo',
                'verbose_name_plural': 'MV_Photos',
                'ordering': ('id',),
            },
        ),
    ]
