# Generated by Django 4.2.16 on 2024-10-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_gallerymv'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'MV_About',
                'verbose_name_plural': 'MV_Abouts',
                'ordering': ('id',),
            },
        ),
    ]
