# Generated by Django 4.2.16 on 2024-10-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_termsconditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsconditions',
            options={'ordering': ('id',), 'verbose_name': 'Term_Condition', 'verbose_name_plural': 'Terms_Conditions'},
        ),
        migrations.AlterField(
            model_name='aboutmv',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='termsconditions',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
