from django.urls import path, re_path
from . import views

app_name = "calculations"
urlpatterns = [
    path("cable_calculation", views.cable_calculation, name = "cable_calculation"),
    path("cable_result", views.cable_result, name = "cable_result"),
    path("protective_choosing", views.protective_choosing, name = "protective_choosing"),
    path("protective_choosing_result", views.protective_choosing_result, name = "protective_choosing_result"),
    path("protective_device", views.protective_device, name = "protective_device"),
    path("protective_device_gauge", views.protective_device_gauge, name = "protective_device_gauge"),
    path("protective_gauge_result", views.protective_gauge_result, name = "protective_gauge_result"),
    path("protective_result", views.protective_result, name = "protective_result"),
    path("drop_voltage", views.drop_voltage, name = "drop_voltage"),
    path("drop_voltage_result", views.drop_voltage_result, name = "drop_voltage_result"),
    path("drop_voltage", views.drop_voltage, name = "drop_voltage"),
    path("grounding_cable", views.grounding_cable, name = "grounding_cable"),
    path("conduit_choosing", views.conduit_choosing, name = "conduit_choosing"),
    path("conduit_choosing_result", views.conduit_choosing_result, name = "conduit_choosing_result"),
    path("conduits_calculation", views.conduit_calculation, name = "conduit_calculation"),
    path("conduits_result", views.conduit_result, name = "conduit_result"),
    path("conduit_gauge_calculation", views.conduit_gauge_calculation, name = "conduit_gauge_calculation"),
    path("conduit_gauge_result", views.conduit_gauge_result, name = "conduit_gauge_result"),
    path("conduit_cable_table", views.conduit_cable_table, name = "conduit_cable_table"),
    path("work_clearances_calculation", views.work_clearances_calculation, name = "work_clearances"),
    path("work_clearances_result", views.work_clearances_result, name = "work_clearances_result"),
    path("safety_clearances_calculation", views.safety_clearances_calculation, name = "safety_clearances"),
    path("safety_clearances_result", views.safety_clearances_result, name = "safety_clearances_result"),
    path("arcflash_calculation", views.arcflash_calculation, name = "arcflash_calculation"),
    path("arcflash_result", views.arcflash_result, name = "arcflash_result"),
    path("arcflash_epps", views.arcflash_epps, name = "arcflash_epps"),
    path("arcflash_gtable", views.arcflash_gtable, name = "arcflash_gtable"),
    path("grounding_cable", views.grounding_cable, name = "grounding_cable"),
    path("grounding_result", views.grounding_result, name = "grounding_result"),
    path("electrode_cable", views.electrode_cable, name = "electrode_cable"),
    path("electrode_result", views.electrode_result, name = "electrode_result"),
    path("cable_choosing", views.cable_choosing, name = "cable_choosing"),
    path("cable_choosing_result", views.cable_choosing_result, name = "cable_choosing_result"),
    path("cable_motor_result", views.cable_motor_result, name = "cable_motor_result"),
    path("cable_motorntc_result", views.cable_motorntc_result, name = "cable_motorntc_result"),
    path('about', views.about, name = 'about'),
]
